-- 문제 25
-- orders 테이블의 주문을 order_id 순으로
-- 정렬하여 누적 주문금액과 3개 주문 이동평균
-- 계산 (ROWS BETWEEN 사용)
-- - SUM(amount) OVER (ORDER BY order_id
--   ROWS BETWEEN UNBOUNDED PRECEDING
--   AND CURRENT ROW)로 누적합 계산
-- - AVG(amount) OVER (ORDER BY order_id
--   ROWS BETWEEN 2 PRECEDING AND
--   CURRENT ROW)로 3개 이동평균 계산
-- - customer_id별로 PARTITION을 나눠 고객
--   별 누적 구매금액도 함께 계산
-- - 누적합이 전체 합의 50%를 초음하는 첫 번
--   째 order_id를 찾는 쿼리를 작성
